### ISSUE TITLE
works for tts?

### ISSUE THREAD

**Issue by kiloptero** [sonocotta/esparagus-media-center#6]

**Comment by anabolyc** [comment]
Hey @kiloptero 

Simple way is to use it with Home Assistant. It will render text on the server side and push it out to the speakers via one of the protocols.

More complicated way is to use native code, you can look into espressif examples: [here](https://github.com/espressif/esp-adf/blob/master/examples/cloud_services/pipeline_aws_polly_mp3/README.md) and [here](https://github.com/espressif/esp-adf/tree/master/examples/cloud_services/google_translate_device)

**Comment by kiloptero** [comment]
if I can see as a media player en Ha its enough!! I don't want to create all my automations again jeje
