### ISSUE TITLE
Can I buy the pre-flashed device in Europe and in Euro currency?

### ISSUE THREAD

**Issue by Dricc123** [sonocotta/esparagus-media-center#7]
the title says it all. Thanks.

**Comment by anabolyc** [comment]
Boards are not generally available while the crowd supply campaign is
running, but i do offer samples to beta testers. Please drop me a line at
***@***.***

**Comment by Dricc123** [comment]
I will wait for now, but thanks. My question was more about whether the boards will be available with shipping within Europe (and sold in euros) one day? Your manufacturing takes place in Europe, correct?

**Comment by anabolyc** [comment]
Yes, absolutely. As someone on as all backers orders are shipped, i’ll
reopen Tindie sales. I ship from Poland, where I assemble, flash ant test
every board myself :)

**Comment by Dricc123** [comment]
But Tindie shows the price in USD currency. Can I change that?

**Comment by anabolyc** [comment]
Tindie only charge USD, but as I said you can contact me directly for custom order.

**Comment by Dricc123** [comment]
I can't find your contact details on your website and Github hides the email address that you wrote down here above

**Comment by anabolyc** [comment]
Oh, sorry, I didn't realize that (probably my email client did)! It is andriy@sonocotta.com. Also, there is a Discord link in my GitHub profile.
